### ISSUE TITLE
The test link does not work

### ISSUE THREAD

**Issue by aoloe** [s3blocks/s3bGenerator#1]
https://scratch.mit.edu/blockify/?id=284721167 points to a whoops page...

**Comment by aoloe** [comment]
ah, sorry... it seems that i need a script manager to be installed before i can try this...

any plan for a standalone website?

**Comment by ZenithRogue** [comment]
Oh yeah, I recommend TamperMonkey for script managing. I do plan on turning it into a full website, and that shouldn't be too difficult. I am just using a userscript for on-the-fly testing

**Comment by aoloe** [comment]
Then I can close this issue : - )

**Comment by ZenithRogue** [comment]
Hey, just wanting to let you know, I just updated the s3blocks homepage, so you can now get the code from a project url!

Please note that reporters and booleans have not yet been implemented, so they wont currently show up.

https://s3blocks.github.io/generator/?id=279911751

**Comment by aoloe** [comment]
yeah, works well!

i'm creating new scratch cards for our coderdojo and your tools are very helpful.

(one day i will probably try to create a plugin for Scribus, so that i can put the "text-code" in there and get the png / svg automatically created : - )

**Comment by eddyparkinson** [comment]
Does not look to work. If I put https://s3blocks.github.io/generator/?id=279911751 in my browser I get blank results back.  Am I missing something?

**Comment by ZenithRogue** [comment]
@eddyparkinson I have no clue what is happening. The link wasnt working for me, but now it suddenly does? This is super weird

**Comment by eddyparkinson** [comment]
@NitroCipher  Looks to need a reload. So with 2 project, the first time I add the url it gives blank results, then if I press the reload on the browser it works correctly.   Thanks.
